[OUTPUT]
# How frequently to save model output (in seconds). Does not need to be a multiple of the domain
output_frequency = 10

[DOMAIN]
# Number of boxes in each dimension. Setting a dimension to 0 will remove it, i.e. with nz = 0, the model is 2D and
# vertical boundary conditions will be ignored
nx = 1
ny = 0
nz = 0

# Time step in seconds.
dt = 1
# How long to run in seconds
run_time = 10800

# Size of the boxes in meters
dx = 1000
dy = 1000
dz = 1000

[TRANSPORT]
do_transport = false
scheme = "implicit2"
wind_type = "fixed"

# Specify the x, y, and z wind speeds in meters/second and diffusion coefficients in m^2/s if using wind_type = fixed
wind_speeds = {x = 5, y = 0, z = 0}
diffusion_coeffs = {x = 1e2, y = 0, z = 0}


[CHEMISTRY]
do_chemistry = true
mechanism = "ideal_first_order"
mechanism_opts = {lifetime_seconds = 3600}
initial_cond = "point"
initial_cond_opts = {center_x = 500, concentration = 1}


[EMISSIONS]
do_emissions = false
# Can be 'gaussian', which will put a Gaussian shaped emission source into the model
emission_type = "point"
emission_opts = {center_x = 500, total = 100}
